# Generated by Django 4.0.6 on 2024-03-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_alter_education_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='course_end_date',
            field=models.TextField(max_length=4),
        ),
    ]
