# Generated by Django 4.0.6 on 2023-11-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.PositiveIntegerField(max_length=10)),
                ('email', models.EmailField(max_length=70)),
                ('Address', models.TextField(max_length=150)),
                ('linkedin', models.URLField(max_length=150)),
                ('github', models.URLField(max_length=150)),
                ('website', models.URLField(max_length=150)),
            ],
        ),
    ]
