# Generated by Django 4.0.6 on 2023-11-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='cv_file',
            field=models.FileField(default=None, max_length=300, null=True, upload_to='cv/'),
        ),
    ]
