# Generated by Django 4.0.6 on 2023-11-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_aboutus_cv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='profile_image',
            field=models.FileField(default=None, max_length=300, null=True, upload_to='profile_img/'),
        ),
    ]
