# Generated by Django 4.0.6 on 2023-11-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='course_description',
            field=models.TextField(max_length=200),
        ),
    ]
