# Generated by Django 4.0.6 on 2024-03-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_project_organisation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=models.TextField(max_length=500),
        ),
    ]
