# Generated by Django 4.0.6 on 2023-11-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=100)),
                ('job_start_date', models.PositiveIntegerField(max_length=4)),
                ('job_end_date', models.PositiveIntegerField(max_length=4)),
                ('job_responsibility', models.TextField(max_length=250)),
            ],
        ),
    ]
