# Generated by Django 4.0.6 on 2023-11-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_name', models.CharField(max_length=50)),
                ('rating', models.PositiveIntegerField(max_length=10)),
            ],
        ),
    ]
